#!/bin/bash
USER=manikant
if [ $# -eq 1 ]; then
    ssh ${USER}@csecourses1.cse.iitk.ac.in "cd cs330assignment3/nachos/code/userprog/;./nachos -x ../test/${1}"
else
    echo 'Give the name of test to run.'
fi
